[package]
name = "hardwareinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
netdev = "0.29.0"
sysinfo = "0.30.12"
starship-battery = "0.8.3"
indexmap = "2.2.6"
nvml-wrapper = "0.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
uuid = { version = "1.6.1", features = ["v4"] }
directories = "4.0.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.4"
libc = "0.2.155"

[target.'cfg(target_os = "linux")'.dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
regex = "1.10.5"
glob = "0.3.1"
