[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="lib"
crate-type = ["dylib", "rlib"]

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
directories = "4.0.1"
powershell_script = "1.0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
wfd = "0.1.7"
