[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="lib"
crate-type = ["dylib", "rlib"]

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
powershell_script = "1.0.4"
wfd = "0.1.7"
