[package]
name = "rtc"
version = "0.1.0"
edition = "2021"

[lib]
name="rtc"
crate-type = ["dylib", "rlib"]

[dependencies]
url = "2.2.2"
tokio = { version = "1.14.0", features = ["full"] }
futures-util = "0.3.21"
tokio-tungstenite = {version = "0.21", features = ["rustls-tls-native-roots"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webrtc = "0.10.1"
tokio-stream = "0.1.14"
log = "0.4.21"
simplelog = "0.12.2"
ezrtc = "0.4.0"
tokio-util = "0.7.11"
once_cell = "1.19.0"
