name: Docker
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              run: |
                  docker buildx build \
                  --platform=linux/amd64,linux/arm64 \
                  -t ghcr.io/levminer/cores/dashboard:latest \
                  --push \
                  --sbom=false \
                  --provenance=false \
                  -f platforms/interface/web/Dockerfile \
                  .
