name: Alpha Unix build

on: push

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: macos-latest
                      NAME: macos
                    - os: ubuntu-latest
                      NAME: linux

        runs-on: ${{ matrix.os}}

        env:
            TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            GH_TOKEN: ${{ github.token }}
            APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
            APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
            APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
            APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
            APPLE_ID: ${{ secrets.APPLE_ID }}
            APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get version
              id: version
              uses: beaconbrigade/package-json-version@v0.3.2
              with:
                  path: .

            - name: Install cross-rs
              run: cargo install cross

            - name: Build service daemon
              if: matrix.NAME == 'linux'
              run: cd platforms/unix/daemon && cargo build --release && cross build --release --target aarch64-unknown-linux-gnu

            - name: Build service daemon
              if: matrix.NAME == 'macos'
              run: cd platforms/unix/daemon && cargo build --release

            - name: Rename service daemon
              run: cp target/release/coresd target/release/coresd-$(rustc -Vv | grep host | cut -f2 -d' ')

            - name: Sign the service daemon
              if: matrix.NAME == 'macos'
              uses: lando/code-sign-action@v2
              with:
                  file: target/release/coresd-aarch64-apple-darwin
                  certificate-data: ${{ secrets.APPLE_CERTIFICATE }}
                  certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
                  apple-notary-user: ${{ secrets.APPLE_ID }}
                  apple-notary-password: ${{ secrets.APPLE_PASSWORD }}
                  apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
                  apple-product-id: com.levminer.coresd
                  options: --options runtime

            - name: Install node modules
              run: npm ci

            - name: Install webkit2gtk (ubuntu only)
              if: matrix.NAME == 'linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            # Build service installer
            - name: Build service installer
              run: npm run build:core

            - name: Remove useless folders
              run: |
                  rm -rf target/release/build
                  rm -rf target/release/deps
                  rm -rf target/release/bundle/appimage/Cores.AppDir
                  npm run rename
              shell: bash

            - name: Zip executables
              if: matrix.NAME == 'linux'
              run: |
                  cd ./target/release/upload
                  zip -r coresd-${{steps.version.outputs.version}}-linux-x64.zip coresd-${{steps.version.outputs.version}}-linux-x64
                  zip -r coresd-${{steps.version.outputs.version}}-linux-arm64.zip coresd-${{steps.version.outputs.version}}-linux-arm64

            # Upload the unpackaged app
            - name: Upload service installer
              uses: actions/upload-artifact@v4
              with:
                  name: "cores-${{matrix.NAME}}-${{runner.arch}}"
                  path: "target/release"

            - name: Run Upload To Release Action
              uses: levminer/upload-to-release@test
              if: startsWith(github.event.ref, 'refs/tags/')
              id: upload
              with:
                  windows-files: "./target/release/upload/cores-%v-windows-x64.msi, ./target/release/upload/cores-%v-windows-x64.zip"
                  macos-files: "./target/release/upload/cores-%v-macos-arm64.dmg"
                  linux-files: "./target/release/upload/cores-%v-linux-x64.appimage, ./target/release/upload/cores-%v-linux-x64.deb, ./target/release/upload/cores-%v-linux-x64.rpm, ./target/release/upload/coresd-%v-linux-arm64.zip, ./target/release/upload/coresd-%v-linux-x64.zip"
